### ISSUE TITLE
right hand side

### ISSUE THREAD

**Issue by lufire** [ZBT-Tools/PEMFC-Model#20]
https://github.com/ZBT-Tools/PEMFC-Model/blob/cf50de038487efd63d4e59e5d844f6fc07d2c301/system/temperature_system.py#L242

The common name in numerics is "right hand side" instead of "right side". The abbreviation rhs is also very common, therefore "update_rhs" and "self.rhs" are better than "update_right_side" and "self.r_s"

**Comment by Simon15043** [comment]
Changed both usages in the files electrical_coupling and temperature_system.
