### ISSUE TITLE
personal directory hard coded

### ISSUE THREAD

**Issue by JakobAntonT** [ZBT-Tools/PEMFC-Model#23]
in pemfc/settings/output.py line 12 the directory is hard coded for the user feierabend, which leads to an error when excecuting the main app

**Comment by lufire** [comment]
thanks for the feedback. at the moment the py-files in the settings-directory are supposed to be the input files, so you need to adjust these including the mentioned line. in the future, i'm thinking of putting it all in a single json-file

**Comment by JakobAntonT** [comment]
All right. I think as a quick solution to this issue, the directory in the output.py could be relative within the python project.

**Comment by lufire** [comment]
yes you're right. updated it
