### ISSUE TITLE
Remove global variables

### ISSUE THREAD

**Issue by lufire** [ZBT-Tools/PEMFC-Model#3]
All functions should rely only on their parameters. Input parameters for the models should be initially read from files and organized into efficient data structures for lookup (dictionaries or sets), which can be passed into the functions

**Comment by lufire** [comment]
https://softwareengineering.stackexchange.com/questions/148108/why-is-global-state-so-evil

**Comment by ZBT-Tools** [comment]
-removed all global parameters
-organized parameters inside classes or file imports
