### ISSUE TITLE
Separate modules

### ISSUE THREAD

**Issue by lufire** [ZBT-Tools/PEMFC-Model#6]
Organize code into smaller fragments (different modules, files). Use one main run function to organize the execution.

**Comment by ZBT-Tools** [comment]
-The code was organized into different files, matching the class shape.

At the moment, the run is structured in the update path, including getter and setter functions.
Updating Simulation determines updating stack, updating stack determines updating cell and so on. 
Building up one main function to organize the run requires direct access to lower class methods.
