### ISSUE TITLE
Review code for simple efficiency

### ISSUE THREAD

**Issue by lufire** [ZBT-Tools/PEMFC-Model#9]
- obvious stuff first; example: rewrite 2.0*10**-2 to 2.0e-2
- try to use numpy routines wherever possible: mathematical operations, array initializations (e.g. numpy.diag) 

further reading:
https://wiki.python.org/moin/PythonSpeed/PerformanceTips
https://www.codementor.io/satwikkansal/python-practices-for-efficient-code-performance-memory-and-usability-aze6oiq65
https://de.slideshare.net/Work-Bench/highperformance-python
etc.

**Comment by ZBT-Tools** [comment]
-rewrote hopefully most numbers
-used numpy functions when possible
